create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  price numeric not null default 0,
  marketplace text not null,
  image text,
  affiliate_url text not null,
  impact text default 'Komisi affiliate mendukung program kebaikan',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.click_events (
  id bigint generated by default as identity primary key,
  product_id uuid references public.products(id) on delete set null,
  marketplace text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.click_events enable row level security;

drop policy if exists "Public can view active products"
on public.products;

create policy "Public can view active products"
on public.products
for select
using (active = true);

drop policy if exists "Public can insert click events"
on public.click_events;

create policy "Public can insert click events"
on public.click_events
for insert
with check (true);

insert into public.products
(name, category, price, marketplace, image, affiliate_url)
values
(
  'Earbuds Wireless',
  'Elektronik',
  199000,
  'Shopee',
  '🎧',
  'https://shopee.co.id/'
),
(
  'Sepatu Running',
  'Fashion',
  329000,
  'TikTok Shop',
  '👟',
  'https://www.tiktok.com/shop'
),
(
  'Blender Portable',
  'Rumah',
  149000,
  'Shopee',
  '🥤',
  'https://shopee.co.id/'
),
(
  'Skincare Basic Set',
  'Kecantikan',
  179000,
  'TikTok Shop',
  '🧴',
  'https://www.tiktok.com/shop'
),
(
  'Keyboard Mechanical',
  'Elektronik',
  399000,
  'Shopee',
  '⌨️',
  'https://shopee.co.id/'
),
(
  'Tas Harian',
  'Fashion',
  129000,
  'TikTok Shop',
  '👜',
  'https://www.tiktok.com/shop'
),
(
  'Lampu Meja LED',
  'Rumah',
  89000,
  'Shopee',
  '💡',
  'https://shopee.co.id/'
),
(
  'Sunscreen',
  'Kecantikan',
  99000,
  'TikTok Shop',
  '☀️',
  'https://www.tiktok.com/shop'
);
